[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120

[tool.pylint.messages_control]
disable = [
  "missing-docstring",
  "line-too-long",
  "too-few-public-methods",
]